# Generated by Django 4.2.7 on 2026-05-26 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('arxiv_id', models.CharField(blank=True, max_length=50)),
                ('local_pdf', models.FileField(upload_to='papers/')),
                ('raw_markdown', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', '待解析'), ('processing', '解析中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExperimentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('metric', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('is_verified', models.BooleanField(default=False)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='papers.paper')),
            ],
            options={
                'ordering': ['dataset', 'model_name'],
            },
        ),
    ]
