# Generated by Django 4.2.7 on 2026-06-09 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='progress_message',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='paper',
            name='status',
            field=models.CharField(choices=[('pending', '待解析'), ('extracting', '提取文本'), ('calling_llm', '调用 LLM'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20),
        ),
    ]
