# Generated by Django 4.2.7 on 2026-06-09 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_session_paper_session_record_benchmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('image', models.ImageField(upload_to='tables/')),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('selected_for_compare', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_images', to='papers.paper')),
            ],
            options={
                'ordering': ['paper', 'page_number', 'order'],
            },
        ),
    ]
