# Generated by Django 4.2.7 on 2026-06-10 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0005_experimentrecord_table_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_n', models.IntegerField()),
                ('page', models.IntegerField()),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('markdown_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_chunks', to='papers.paper')),
            ],
            options={
                'ordering': ['paper', 'page', 'table_n'],
                'unique_together': {('paper', 'table_n')},
            },
        ),
        migrations.AddField(
            model_name='experimentrecord',
            name='table_chunk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='papers.tablechunk'),
        ),
    ]
