# Generated by Django 4.2.7 on 2026-06-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0006_tablechunk_experimentrecord_table_chunk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tablechunk',
            options={'ordering': ['paper', 'page', 'table_n', 'sub_table_index']},
        ),
        migrations.AlterUniqueTogether(
            name='tablechunk',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tablechunk',
            name='bbox_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tablechunk',
            name='cells_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tablechunk',
            name='extraction_method',
            field=models.CharField(choices=[('find_tables', 'find_tables'), ('pymupdf4llm_fallback', 'pymupdf4llm_fallback')], default='find_tables', max_length=24),
        ),
        migrations.AddField(
            model_name='tablechunk',
            name='header_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tablechunk',
            name='parent_table_n',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tablechunk',
            name='sub_table_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='tablechunk',
            unique_together={('paper', 'table_n', 'sub_table_index')},
        ),
    ]
