# Generated by Django 4.2.30 on 2026-06-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0008_alter_tablechunk_extraction_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablechunk',
            name='extraction_method',
            field=models.CharField(choices=[('docling', 'docling'), ('camelot_stream', 'camelot_stream'), ('camelot_lattice', 'camelot_lattice'), ('pymupdf_find_tables', 'pymupdf_find_tables'), ('pymupdf4llm', 'pymupdf4llm')], default='camelot_stream', max_length=24),
        ),
    ]
