# Generated by Django 4.2.30 on 2026-06-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0009_alter_tablechunk_extraction_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablechunk',
            name='tags',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
