# Generated by Django 4.2.30 on 2026-06-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0010_add_tags_to_tablechunk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentrecord',
            name='table_image',
        ),
        migrations.AlterField(
            model_name='tablechunk',
            name='extraction_method',
            field=models.CharField(choices=[('docling', 'docling')], default='docling', max_length=24),
        ),
        migrations.DeleteModel(
            name='TableImage',
        ),
    ]
